## The logic is fairly similar to the Analyst and Planner agents

import json
from ollama import chat


## System prompt for the Developer Agent
## The Developer Agent receives the plan from the Planner Agent
## and converts the plan into valid Python navigation code.

system_prompt = """
You are a Developer Agent for a robot navigation system.

Your task is to convert the validated navigation plan provided by
the Planner Agent into valid Python code.

The generated Python code must contain exactly one main navigation
function called:

decide_action(front_blocked, left_blocked, right_blocked, goal_direction)

The function must return only one of:

FORWARD
LEFT
RIGHT
STOP

IMPORTANT DECISION ORDER:

1. FIRST check goal_direction.

2. If goal_direction == "ahead" and front_blocked is False:
   return "FORWARD".

3. If goal_direction == "left" and left_blocked is False:
   return "LEFT".

4. If goal_direction == "right" and right_blocked is False:
   return "RIGHT".

5. ONLY when the goal direction is blocked or unknown,
   use this fallback order:

   FORWARD
   LEFT
   RIGHT

6. Never move into a blocked direction.

7. If front, left, and right are all blocked:
   return "STOP".

IMPORTANT:
Do NOT automatically return FORWARD just because the front is clear.
The goal direction must always be checked first.

Example:

If:
front_blocked = False
left_blocked = False
right_blocked = False
goal_direction = "left"

the result MUST be:

LEFT

It must NOT be FORWARD.

Return Python code only.
Do not use Markdown code blocks.
Do not include explanations before or after the code.
"""

## Function to validate the Python code generated by the Developer Agent
def validate_code(code):

    # Check that the result is a string
    if not isinstance(code, str):
        raise ValueError("Generated code must be a string.")

    if code.strip() == "":
        raise ValueError("Generated code cannot be empty.")

    # Check that the code is valid Python syntax
    try:
        compile(
            code,
            "navigation_logic.py",
            "exec"
        )

    except SyntaxError as error:
        raise ValueError(
            f"Generated code is not valid Python: {error}"
        )

    # Check that the required navigation function exists
    if "def decide_action" not in code:
        raise ValueError(
            "Generated code must contain a decide_action function."
        )

    # Run the generated code in a separate namespace
    namespace = {}

    exec(code, namespace)

    if "decide_action" not in namespace:
        raise ValueError(
            "decide_action function was not created."
        )

    decide_action = namespace["decide_action"]

    # Test 1:
    # Goal is ahead and front is clear
    result = decide_action(
        False,
        False,
        False,
        "ahead"
    )

    if result != "FORWARD":
        raise ValueError(
            "When the goal is ahead and the front is clear, "
            "the action must be FORWARD."
        )

    # Test 2:
    # Goal is left and left is clear
    result = decide_action(
        False,
        False,
        False,
        "left"
    )

    if result != "LEFT":
        raise ValueError(
            "When the goal is left and the left path is clear, "
            "the action must be LEFT."
        )

    # Test 3:
    # Goal is right and right is clear
    result = decide_action(
        False,
        False,
        False,
        "right"
    )

    if result != "RIGHT":
        raise ValueError(
            "When the goal is right and the right path is clear, "
            "the action must be RIGHT."
        )

    # Test 4:
    # Goal is left but left is blocked.
    # Front is clear, so use fallback FORWARD.
    result = decide_action(
        False,
        True,
        False,
        "left"
    )

    if result != "FORWARD":
        raise ValueError(
            "When the goal direction is blocked, "
            "the fallback order should start with FORWARD."
        )

    # Test 5:
    # All directions are blocked
    result = decide_action(
        True,
        True,
        True,
        "ahead"
    )

    if result != "STOP":
        raise ValueError(
            "When all directions are blocked, "
            "the action must be STOP."
        )

    return True


## Function to run the Developer Agent
## It takes the plan generated by the Planner Agent,
## sends it to Qwen, validates the generated Python code,
## and returns the validated code.
def run_developer(plan):

    # Make sure the plan is a dictionary
    if not isinstance(plan, dict):
        raise ValueError("Plan must be a dictionary.")

    # Convert the plan into text
    plan_text = json.dumps(
        plan,
        indent=4
    )

    prompt = f"""
Create Python navigation code based on the following validated plan:

{plan_text}

Return Python code only.
"""

    # Send the plan to Qwen
    response = chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    # Get the generated code
    code = response["message"]["content"].strip()

    # Remove Markdown code blocks if Qwen adds them
    if code.startswith("```python"):
        code = code[9:]

    elif code.startswith("```"):
        code = code[3:]

    if code.endswith("```"):
        code = code[:-3]

    code = code.strip()

    # Validate the generated Python code
    validate_code(code)

    # Return the validated code
    return code