import json
from ollama import chat

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.

system_prompt = """
You are a Planner Agent for a robot navigation system.

Your task is to create a navigation plan based only on the validated
requirements provided by the Analyst Agent.

The robot is allowed to use only these actions:
FORWARD
LEFT
RIGHT
STOP

Return ONLY a valid JSON object with exactly this structure:

{
    "strategy": "A clear strategy describing how the robot should navigate",
    "decisions": [
        {
            "condition": "A navigation condition",
            "action": "FORWARD"
        }
    ],
    "stop_condition": "A clear condition describing when the robot must stop"
}

Rules:
1. Use only FORWARD, LEFT, RIGHT, and STOP as actions.

2. The robot must prioritize movement toward the goal direction
   whenever that direction is not blocked.

3. If the goal is ahead and the front is clear, use FORWARD.

4. If the goal is left and the left direction is clear, use LEFT.

5. If the goal is right and the right direction is clear, use RIGHT.

6. If the goal direction is blocked or unknown, check other safe
   directions in this fallback order:
   FORWARD, LEFT, RIGHT.

7. The robot must never move into a blocked direction.

8. The decisions list must include conditions for:
   FORWARD, LEFT, RIGHT, and STOP.

9. If all directions are blocked, use STOP.

10. Do not add any extra keys.

11. Return JSON only.

12. Do not include Markdown or explanations outside the JSON.
"""


## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type. 
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):

    # Check that the plan is a dictionary
    if not isinstance(data, dict):
        raise ValueError("Plan must be a dictionary.")

    # Check that the plan has exactly the required keys
    required_keys = {
        "strategy",
        "decisions",
        "stop_condition"
    }

    if set(data.keys()) != required_keys:
        raise ValueError(
            "Plan must contain exactly strategy, decisions, and stop_condition."
        )

    # Check strategy
    if not isinstance(data["strategy"], str):
        raise ValueError("strategy must be a string.")

    if data["strategy"].strip() == "":
        raise ValueError("strategy cannot be empty.")

    # Check decisions
    if not isinstance(data["decisions"], list):
        raise ValueError("decisions must be a list.")

    if len(data["decisions"]) == 0:
        raise ValueError("decisions cannot be empty.")

    allowed_actions = {
        "FORWARD",
        "LEFT",
        "RIGHT",
        "STOP"
    }

    actions_in_plan = set()

    for decision in data["decisions"]:

        if not isinstance(decision, dict):
            raise ValueError("Each decision must be a dictionary.")

        if set(decision.keys()) != {"condition", "action"}:
            raise ValueError(
                "Each decision must contain exactly condition and action."
            )

        if not isinstance(decision["condition"], str):
            raise ValueError("condition must be a string.")

        if not isinstance(decision["action"], str):
            raise ValueError("action must be a string.")

        if decision["action"] not in allowed_actions:
            raise ValueError(
                f"Invalid action: {decision['action']}"
            )

        actions_in_plan.add(decision["action"])

    if actions_in_plan != allowed_actions:
        raise ValueError(
            "Plan must include FORWARD, LEFT, RIGHT, and STOP decisions."
        )

    # Check stop condition
    if not isinstance(data["stop_condition"], str):
        raise ValueError("stop_condition must be a string.")

    if data["stop_condition"].strip() == "":
        raise ValueError("stop_condition cannot be empty.")

    return True


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):

    # Make sure the requirement is a dictionary
    if not isinstance(requirement, dict):
        raise ValueError("Requirement must be a dictionary.")

    # Convert the requirement dictionary into text
    requirement_text = json.dumps(
        requirement,
        indent=4
    )

    prompt = f"""
Create a navigation plan based on the following validated requirements:

{requirement_text}

Return only the required JSON object.
"""

    # Send the requirements to Qwen
    response = chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    # Get the response text
    result = response["message"]["content"].strip()

    # Remove Markdown code blocks if Qwen adds them
    if result.startswith("```json"):
        result = result[7:]

    elif result.startswith("```"):
        result = result[3:]

    if result.endswith("```"):
        result = result[:-3]

    result = result.strip()

    # Find the JSON part of the response
    start = result.find("{")
    end = result.rfind("}")

    if start == -1 or end == -1:
        raise ValueError("Planner Agent did not return valid JSON.")

    result = result[start:end + 1]

    # Convert JSON text into a Python dictionary
    plan = json.loads(result)

    # Validate the plan
    validate_plan(plan)

    # Return the validated plan
    return plan