## the logic is similar to the run_planner and run_analyst files

import json
from pathlib import Path

from developer_agent import run_developer


# Read the validated plan generated by the Planner Agent
with open(
    "artifacts/plan.json",
    "r",
    encoding="utf-8"
) as file:
    plan = json.load(file)


# Call the Developer Agent
code = run_developer(plan)


# Save the generated Python code
Path("navigation_logic.py").write_text(
    code,
    encoding="utf-8"
)


print("Navigation code saved to navigation_logic.py")