import json
from pathlib import Path

from planner_agent import run_planner


## Create a function/logic that reads the requirements from requirements.json, 
# then calls the run_planner function with the requirements as input, and finally writes the validated plan to plan.json. 

# Read the validated requirements generated by the Analyst Agent
with open(
    "artifacts/requirements.json",
    "r",
    encoding="utf-8"
) as file:
    requirements = json.load(file)


# Call the Planner Agent
plan = run_planner(requirements)


# Create the artifacts folder if it does not exist
Path("artifacts").mkdir(exist_ok=True)


# Save the validated plan
with open(
    "artifacts/plan.json",
    "w",
    encoding="utf-8"
) as file:
    json.dump(
        plan,
        file,
        indent=4
    )


print("Plan saved to artifacts/plan.json")